### ISSUE TITLE
Not compatible

### ISSUE THREAD

**Issue by Psycarlo** [akshitkrnagpal/gatsby-plugin-chatwoot#7]
I am running gatsby version `^4.11.1`, so when I install this plugin, I get:

`Plugin gatsby-plugin-chatwoot is not compatible with your gatsby version 4.11.1 - It requires gatsby@^2.19.5`.

Any ideas on how I can get this fixed?

**Comment by akshitkrnagpal** [comment]
Hi @Psycarlo 

I assume you are only getting a warning?

This is because this plugin doesn't have updated peer dependencies. If the chatwoot widget is being shown on your gatsby project, you can ignore this warning. I have created a PR (#8) for it, the warning will be fixed in future versions.
